### ISSUE TITLE
Function Definitions not working between two Included scripts

### ISSUE THREAD

**Issue by oakwoodwolf** [denesfilotas/vscode-blitz3d#1]
Hello, I am working on bigger projects with this and the bbdoc does not work well with it. I have a bunch of includes in the main bb file, and it works fine. (i.e. this is on Sonic World.bb, pointing to the function definition correctly).
![image](https://user-images.githubusercontent.com/12115201/196444292-8eaf3179-2cf7-4b99-97b7-980260540480.png)

Although in the included .bb files, it calls to functions from a Core_Tools.bb, but it fails to notice the definition.
Here is the definition in the Core_Tools.bb:
![image](https://user-images.githubusercontent.com/12115201/196445010-a3dce617-ed85-4052-ba0c-7237bd56728c.png)

It is called in an function to a script included in the Sonic World.bb, but it struggles to find the origin.
As seen here: it is called upon in Chao_Emo.bb, but cannot find the definition, unlike the Game_Update() function.
![image](https://user-images.githubusercontent.com/12115201/196445788-f374ab5f-7036-4542-bfc7-b01a54baf13f.png)

Building is not affected by this and functions as normal.
Is there a way this extension could support this somehow?

If you need to reference the code, it is an edited version of [this repository](https://github.com/Syllenze/Blitz3D-Sonic-World-Engine):

**Comment by denesfilotas** [comment]
Hi,

Thanks for reaching out. I'm more than happy to help, though I can't guarantee anything immediately as my midterms are coming next week.

From what I understand, this is the expected behavior. When processing a file, the extension only checks the files explicitly included in that file. It's impossible to determine statically which files will be loaded and which functions will be available on runtime from an included file on its own, it depends on the main program file which will be run.

What I could think of as a solution would be to build a document tree based on the main file selected for each launch configuration. Then the extension could search the whole tree for functions, variables etc to be included. This tree could easily be constructed automatically, extending functionality for the `bbfile` build config.

Currently the include detection system is quite messed up anyways. Dynamically obtained filenames (e.g. `Include "file" + var$ + ".bb"`) and relative paths (especially includes in an included file) are rarely processed correctly. Using the document tree, it would also be possible to add unrecognized include files manually.

I hope implementing a feature like this in the near future would suffice your needs. Feel free to leave additional comments or suggestions, if you have any.

**Comment by oakwoodwolf** [comment]
Brilliant. Thank you very much. That is pretty much my only gripe with this. At this rate I may transfer my workflow from IDEal to vscode thanks to this extension.

**Comment by denesfilotas** [comment]
Starting in the next version, the extension will recognize items from every file included in the `bbfile` selected in the launch config.
