### ISSUE TITLE
Nested Includes don't work

### ISSUE THREAD

**Issue by Aryan807** [denesfilotas/vscode-blitz3d#4]
It seems I have found another issue: nested Includes don't work.

Say for example I made a file "test.bb" referencing "folder/test1.bb" in a folder "folder" and the latter file referencing "folder/test2.bb" then I get error in "folder/test1.bb" that test2.bb was not found. "test.bb" works fine though.

![image](https://github.com/denesfilotas/vscode-blitz3d/assets/52038234/e380284d-7fd2-4af2-846f-f846bf54a698)

This issue was not present in v0.4.x releases

_Originally posted by @Aryan807 in https://github.com/denesfilotas/vscode-blitz3d/issues/3#issuecomment-2016334806_

**Comment by denesfilotas** [comment]
Thanks for the feedback!

The new parser does not track the directory where the program runs, it uses the path of the importing file to guess that.

I will take a look and re-implement the old behavior, perhaps with an appropriate launch config to cd into before running.

**Comment by denesfilotas** [comment]
I think I got it figured out. The include path used by blitz is always the directory containing the file to be run. So the workspace folder is only correct if the file is at the workspace root. I implemented the correct behaviour, however, it is still far from perfect if there are multiple (or no) launch configurations or multiple folders open in a workspace. I will get back to this when I have time.

Closing this since nested includes do work now for the bbfile specified in launch config and everything it references.
